### ISSUE TITLE
Chinese Tribal Innovation Discussion

### ISSUE THREAD

**Issue by dragoon-103** [dragoon-103/AsiaExtended#1]
What are the current plans regarding the chinese innovations? Are we going to make it so that each area of china have their own individual MAA, or are we gonig to try and truncate it down to either 1 or 2 MAA for the culture itself.

Also not sure if all these innovations are holdovers.

![image](https://user-images.githubusercontent.com/10717495/150618479-c9b47ce3-edd8-4fd2-93dd-1125b0f71d33.png)

**Comment by Eisprinzessin** [comment]
i will take a look later and then i can say waht we use and waht can be deletet

**Comment by dragoon-103** [comment]
Discussed and Removed extra chinese innovations
